def _quote(s):
    return "'" + s.replace("'", "'\\''") + "'"

def openblas_wrapped_c(name, src, symbol, defines = []):
    lines = [
        "/* Generated by Bazel. */",
        "#define OPENBLAS_BAZEL 1",
        "#define CNAME %s" % symbol,
        "#define CHAR_CNAME \"%s\"" % symbol,
        "#define NAME %s" % symbol,
        "#define CHAR_NAME \"%s\"" % symbol,
    ]

    for define in defines:
        if "=" in define:
            key, value = define.split("=", 1)
            lines.append("#define %s %s" % (key, value))
        else:
            lines.append("#define %s 1" % define)

    lines.append("")

    native.genrule(
        name = name,
        srcs = [src],
        outs = [name + ".c"],
        cmd = "printf %s > $@ && cat $(location %s) >> $@" % (
            _quote("\\n".join(lines)),
            src,
        ),
    )

def _openblas_object(targets, name, src, symbol, defines = []):
    target_name = name + "_src"
    openblas_wrapped_c(
        name = target_name,
        src = src,
        defines = defines,
        symbol = symbol,
    )
    targets.append(":" + target_name)

def _add_netlib_getri(targets, precision):
    prefix = precision.prefix
    _openblas_object(
        targets = targets,
        name = "%sgetri" % prefix,
        src = "lapack-netlib/SRC/%sgetri.c" % prefix,
        defines = [
            "%sgetri_=%sgetri" % (prefix, prefix),
            "%sgemm_=%sgemm" % (prefix, prefix),
            "%sgemv_=%sgemv" % (prefix, prefix),
            "%sswap_=%sswap" % (prefix, prefix),
            "%strsm_=%strsm" % (prefix, prefix),
            "%strtri_=%strtri" % (prefix, prefix),
            "ilaenv_=openblas_bazel_ilaenv",
        ],
        symbol = "%sgetri" % prefix,
    )

def openblas_real_targets():
    targets = []

    _openblas_object(
        targets = targets,
        name = "xerbla",
        src = "driver/others/xerbla.c",
        symbol = "xerbla",
    )
    _openblas_object(
        targets = targets,
        name = "parameter",
        src = "driver/others/parameter.c",
        symbol = "blas_set_parameter",
    )

    for precision in [
        struct(prefix = "s", c_type_defines = [], kernel_defines = []),
        struct(prefix = "d", c_type_defines = ["DOUBLE"], kernel_defines = ["DOUBLE"]),
    ]:
        for op in [
            struct(name = "axpy", src = "interface/axpy.c", kernel_src = "kernel/arm/axpy.c"),
            struct(name = "copy", src = "interface/copy.c", kernel_src = "kernel/arm/copy.c"),
            struct(name = "swap", src = "interface/swap.c", kernel_src = "kernel/arm/swap.c"),
            struct(name = "scal", src = "interface/scal.c", kernel_src = "kernel/arm/scal.c"),
            struct(name = "dot", src = "interface/dot.c", kernel_src = "kernel/arm/dot.c"),
            struct(name = "asum", src = "interface/asum.c", kernel_src = "kernel/arm/asum.c"),
            struct(name = "nrm2", src = "interface/nrm2.c", kernel_src = "kernel/arm/nrm2.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s" % (precision.prefix, op.name),
                src = op.src,
                defines = ["CBLAS"] + precision.c_type_defines,
                symbol = "cblas_%s%s" % (precision.prefix, op.name),
            )
            _openblas_object(
                targets = targets,
                name = "%s%s_kernel" % (precision.prefix, op.name),
                src = op.kernel_src,
                defines = precision.kernel_defines,
                symbol = "%s%s_k" % (precision.prefix, op.name),
            )
        _openblas_object(
            targets = targets,
            name = "%sswap" % precision.prefix,
            src = "interface/swap.c",
            defines = precision.c_type_defines,
            symbol = "%sswap" % precision.prefix,
        )
        for amin_op in [
            struct(name = "amin", src = "kernel/arm/amin.c", symbol = "%samin_k" % precision.prefix),
            struct(name = "iamin", src = "kernel/arm/iamin.c", symbol = "i%samin_k" % precision.prefix),
        ]:
            _openblas_object(
                targets = targets,
                name = "%s%s_kernel" % (precision.prefix, amin_op.name),
                src = amin_op.src,
                defines = precision.kernel_defines,
                symbol = amin_op.symbol,
            )

    for index_fn in [
        struct(prefix = "s", suffix = "amax", src = "interface/imax.c", kernel = "kernel/arm/iamax.c", defines = ["CBLAS", "USE_ABS"]),
        struct(prefix = "d", suffix = "amax", src = "interface/imax.c", kernel = "kernel/arm/iamax.c", defines = ["CBLAS", "DOUBLE", "USE_ABS"]),
    ]:
        _openblas_object(
            targets = targets,
            name = "cblas_i%s%s" % (index_fn.prefix, index_fn.suffix),
            src = index_fn.src,
            defines = index_fn.defines,
            symbol = "cblas_i%s%s" % (index_fn.prefix, index_fn.suffix),
        )
        _openblas_object(
            targets = targets,
            name = "i%s%s_kernel" % (index_fn.prefix, index_fn.suffix),
            src = index_fn.kernel,
            defines = [d for d in index_fn.defines if d in ["DOUBLE"]],
            symbol = "i%s%s_k" % (index_fn.prefix, index_fn.suffix),
        )

    for precision in [
        struct(prefix = "s", c_type_defines = [], kernel_defines = []),
        struct(prefix = "d", c_type_defines = ["DOUBLE"], kernel_defines = ["DOUBLE"]),
    ]:
        _openblas_object(
            targets = targets,
            name = "cblas_%sgemm" % precision.prefix,
            src = "interface/gemm.c",
            defines = ["CBLAS"] + precision.c_type_defines,
            symbol = "cblas_%sgemm" % precision.prefix,
        )
        _openblas_object(
            targets = targets,
            name = "%sgemm" % precision.prefix,
            src = "interface/gemm.c",
            defines = precision.c_type_defines,
            symbol = "%sgemm" % precision.prefix,
        )
        for gemm_variant in [
            struct(suffix = "nn", defines = ["NN"]),
            struct(suffix = "nt", defines = ["NT"]),
            struct(suffix = "tn", defines = ["TN"]),
            struct(suffix = "tt", defines = ["TT"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%sgemm_%s" % (precision.prefix, gemm_variant.suffix),
                src = "driver/level3/gemm.c",
                defines = precision.kernel_defines + gemm_variant.defines,
                symbol = "%sgemm_%s" % (precision.prefix, gemm_variant.suffix),
            )
        gemm_kernels = [
            struct(name = "gemm_kernel", src = "kernel/generic/gemmkernel_2x2.c", symbol = "gemm_kernel"),
            struct(name = "gemm_beta", src = "kernel/generic/gemm_beta.c", symbol = "gemm_beta"),
            struct(name = "gemm_oncopy", src = "kernel/generic/gemm_ncopy_2.c", symbol = "gemm_oncopy"),
            struct(name = "gemm_otcopy", src = "kernel/generic/gemm_tcopy_2.c", symbol = "gemm_otcopy"),
        ]

        if precision.prefix == "s":
            gemm_kernels = [
                struct(name = "gemm_kernel", src = "kernel/x86_64/sgemm_kernel_8x4_haswell_2.c", symbol = "gemm_kernel"),
                struct(name = "gemm_beta", src = "kernel/x86_64/sgemm_beta_skylakex.c", symbol = "gemm_beta"),
                struct(name = "gemm_oncopy", src = "kernel/x86_64/sgemm_ncopy_4_skylakex.c", symbol = "gemm_oncopy"),
                struct(name = "gemm_otcopy", src = "kernel/generic/gemm_tcopy_4.c", symbol = "gemm_otcopy"),
            ]

        for gemm_kernel in gemm_kernels:
            _openblas_object(
                targets = targets,
                name = "%s%s" % (precision.prefix, gemm_kernel.name),
                src = gemm_kernel.src,
                defines = precision.kernel_defines,
                symbol = "%s%s" % (precision.prefix, gemm_kernel.symbol),
            )
        _openblas_object(
            targets = targets,
            name = "cblas_%ssymm" % precision.prefix,
            src = "interface/symm.c",
            defines = ["CBLAS"] + precision.c_type_defines,
            symbol = "cblas_%ssymm" % precision.prefix,
        )
        for symm_variant in [
            struct(name = "LU", defines = ["NN"]),
            struct(name = "LL", defines = ["LOWER", "NN"]),
            struct(name = "RU", defines = ["RSIDE", "NN"]),
            struct(name = "RL", defines = ["RSIDE", "LOWER", "NN"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%ssymm_%s" % (precision.prefix, symm_variant.name.lower()),
                src = "driver/level3/symm_k.c",
                defines = precision.kernel_defines + symm_variant.defines,
                symbol = "%ssymm_%s" % (precision.prefix, symm_variant.name),
            )
        for symm_copy in [
            struct(name = "symm_outcopy", src = "kernel/generic/symm_ucopy_2.c", symbol = "symm_outcopy"),
            struct(name = "symm_oltcopy", src = "kernel/generic/symm_lcopy_2.c", symbol = "symm_oltcopy"),
        ]:
            _openblas_object(
                targets = targets,
                name = "%s%s" % (precision.prefix, symm_copy.name),
                src = symm_copy.src,
                defines = precision.kernel_defines,
                symbol = "%s%s" % (precision.prefix, symm_copy.symbol),
            )
        for symmetric_rankk in [
            struct(name = "syrk", interface_src = "interface/syrk.c", driver_src = "driver/level3/syrk_k.c", kernel_src = "driver/level3/syrk_kernel.c"),
            struct(name = "syr2k", interface_src = "interface/syr2k.c", driver_src = "driver/level3/syr2k_k.c", kernel_src = "driver/level3/syr2k_kernel.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s" % (precision.prefix, symmetric_rankk.name),
                src = symmetric_rankk.interface_src,
                defines = ["CBLAS"] + precision.c_type_defines,
                symbol = "cblas_%s%s" % (precision.prefix, symmetric_rankk.name),
            )
            for rankk_variant in [
                struct(name = "UN", defines = []),
                struct(name = "UT", defines = ["TRANS"]),
                struct(name = "LN", defines = ["LOWER"]),
                struct(name = "LT", defines = ["LOWER", "TRANS"]),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_%s" % (precision.prefix, symmetric_rankk.name, rankk_variant.name.lower()),
                    src = symmetric_rankk.driver_src,
                    defines = precision.kernel_defines + rankk_variant.defines,
                    symbol = "%s%s_%s" % (precision.prefix, symmetric_rankk.name, rankk_variant.name),
                )
            for uplo_variant in [
                struct(suffix = "u", symbol_suffix = "U", defines = []),
                struct(suffix = "l", symbol_suffix = "L", defines = ["LOWER"]),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_kernel_%s" % (precision.prefix, symmetric_rankk.name, uplo_variant.suffix),
                    src = symmetric_rankk.kernel_src,
                    defines = precision.kernel_defines + uplo_variant.defines,
                    symbol = "%s%s_kernel_%s" % (precision.prefix, symmetric_rankk.name, uplo_variant.symbol_suffix),
                )
        for triangular_level3 in [
            struct(name = "trmm", c_defines = ["CBLAS", "TRMM"], left_src = "driver/level3/trmm_L.c", right_src = "driver/level3/trmm_R.c", copy_prefix = "trmm", kernel_prefix = "trmm"),
            struct(name = "trsm", c_defines = ["CBLAS"], left_src = "driver/level3/trsm_L.c", right_src = "driver/level3/trsm_R.c", copy_prefix = "trsm", kernel_prefix = "trsm"),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s" % (precision.prefix, triangular_level3.name),
                src = "interface/trsm.c",
                defines = triangular_level3.c_defines + precision.c_type_defines,
                symbol = "cblas_%s%s" % (precision.prefix, triangular_level3.name),
            )
            if triangular_level3.name == "trsm":
                _openblas_object(
                    targets = targets,
                    name = "%s%s" % (precision.prefix, triangular_level3.name),
                    src = "interface/trsm.c",
                    defines = precision.c_type_defines,
                    symbol = "%s%s" % (precision.prefix, triangular_level3.name),
                )
            for tri_variant in [
                struct(name = "LNUU", src = triangular_level3.left_src, defines = ["UPPER", "UNIT"]),
                struct(name = "LNUN", src = triangular_level3.left_src, defines = ["UPPER"]),
                struct(name = "LNLU", src = triangular_level3.left_src, defines = ["UNIT"]),
                struct(name = "LNLN", src = triangular_level3.left_src, defines = []),
                struct(name = "LTUU", src = triangular_level3.left_src, defines = ["TRANSA", "UPPER", "UNIT"]),
                struct(name = "LTUN", src = triangular_level3.left_src, defines = ["TRANSA", "UPPER"]),
                struct(name = "LTLU", src = triangular_level3.left_src, defines = ["TRANSA", "UNIT"]),
                struct(name = "LTLN", src = triangular_level3.left_src, defines = ["TRANSA"]),
                struct(name = "RNUU", src = triangular_level3.right_src, defines = ["UPPER", "UNIT"]),
                struct(name = "RNUN", src = triangular_level3.right_src, defines = ["UPPER"]),
                struct(name = "RNLU", src = triangular_level3.right_src, defines = ["UNIT"]),
                struct(name = "RNLN", src = triangular_level3.right_src, defines = []),
                struct(name = "RTUU", src = triangular_level3.right_src, defines = ["TRANSA", "UPPER", "UNIT"]),
                struct(name = "RTUN", src = triangular_level3.right_src, defines = ["TRANSA", "UPPER"]),
                struct(name = "RTLU", src = triangular_level3.right_src, defines = ["TRANSA", "UNIT"]),
                struct(name = "RTLN", src = triangular_level3.right_src, defines = ["TRANSA"]),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_%s" % (precision.prefix, triangular_level3.name, tri_variant.name.lower()),
                    src = tri_variant.src,
                    defines = precision.kernel_defines + tri_variant.defines,
                    symbol = "%s%s_%s" % (precision.prefix, triangular_level3.name, tri_variant.name),
                )
            for copy_variant in [
                struct(name = "ounucopy", src = "kernel/generic/%s_uncopy_2.c" % triangular_level3.copy_prefix, defines = ["UNIT"]),
                struct(name = "ounncopy", src = "kernel/generic/%s_uncopy_2.c" % triangular_level3.copy_prefix, defines = []),
                struct(name = "outucopy", src = "kernel/generic/%s_utcopy_2.c" % triangular_level3.copy_prefix, defines = ["UNIT"]),
                struct(name = "outncopy", src = "kernel/generic/%s_utcopy_2.c" % triangular_level3.copy_prefix, defines = []),
                struct(name = "olnucopy", src = "kernel/generic/%s_lncopy_2.c" % triangular_level3.copy_prefix, defines = ["UNIT"]),
                struct(name = "olnncopy", src = "kernel/generic/%s_lncopy_2.c" % triangular_level3.copy_prefix, defines = []),
                struct(name = "oltucopy", src = "kernel/generic/%s_ltcopy_2.c" % triangular_level3.copy_prefix, defines = ["UNIT"]),
                struct(name = "oltncopy", src = "kernel/generic/%s_ltcopy_2.c" % triangular_level3.copy_prefix, defines = []),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_%s" % (precision.prefix, triangular_level3.copy_prefix, copy_variant.name),
                    src = copy_variant.src,
                    defines = precision.kernel_defines + copy_variant.defines,
                    symbol = "%s%s_%s" % (precision.prefix, triangular_level3.copy_prefix, copy_variant.name),
                )
        for trmm_kernel in [
            struct(name = "LN", defines = ["TRMMKERNEL", "LEFT"]),
            struct(name = "LT", defines = ["TRMMKERNEL", "LEFT", "TRANSA"]),
            struct(name = "RN", defines = ["TRMMKERNEL"]),
            struct(name = "RT", defines = ["TRMMKERNEL", "TRANSA"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%strmm_kernel_%s" % (precision.prefix, trmm_kernel.name.lower()),
                src = "kernel/generic/trmmkernel_2x2.c",
                defines = precision.kernel_defines + trmm_kernel.defines,
                symbol = "%strmm_kernel_%s" % (precision.prefix, trmm_kernel.name),
            )
        for trsm_kernel in [
            struct(name = "LN", src = "kernel/generic/trsm_kernel_LN.c"),
            struct(name = "LT", src = "kernel/generic/trsm_kernel_LT.c"),
            struct(name = "RN", src = "kernel/generic/trsm_kernel_RN.c"),
            struct(name = "RT", src = "kernel/generic/trsm_kernel_RT.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "%strsm_kernel_%s" % (precision.prefix, trsm_kernel.name.lower()),
                src = trsm_kernel.src,
                defines = precision.kernel_defines,
                symbol = "%strsm_kernel_%s" % (precision.prefix, trsm_kernel.name),
            )
        _openblas_object(
            targets = targets,
            name = "cblas_%sgemv" % precision.prefix,
            src = "interface/gemv.c",
            defines = ["CBLAS"] + precision.c_type_defines,
            symbol = "cblas_%sgemv" % precision.prefix,
        )
        _openblas_object(
            targets = targets,
            name = "%sgemv" % precision.prefix,
            src = "interface/gemv.c",
            defines = precision.c_type_defines,
            symbol = "%sgemv" % precision.prefix,
        )
        _openblas_object(
            targets = targets,
            name = "%sgemv_n_kernel" % precision.prefix,
            src = "kernel/arm/gemv_n.c",
            defines = precision.kernel_defines,
            symbol = "%sgemv_n" % precision.prefix,
        )
        _openblas_object(
            targets = targets,
            name = "%sgemv_t_kernel" % precision.prefix,
            src = "kernel/arm/gemv_t.c",
            defines = precision.kernel_defines,
            symbol = "%sgemv_t" % precision.prefix,
        )
        _openblas_object(
            targets = targets,
            name = "cblas_%sger" % precision.prefix,
            src = "interface/ger.c",
            defines = ["CBLAS"] + precision.c_type_defines,
            symbol = "cblas_%sger" % precision.prefix,
        )
        _openblas_object(
            targets = targets,
            name = "%sger_kernel" % precision.prefix,
            src = "kernel/generic/ger.c",
            defines = precision.kernel_defines,
            symbol = "%sger_k" % precision.prefix,
        )
        _openblas_object(
            targets = targets,
            name = "cblas_%ssymv" % precision.prefix,
            src = "interface/symv.c",
            defines = ["CBLAS"] + precision.c_type_defines,
            symbol = "cblas_%ssymv" % precision.prefix,
        )
        _openblas_object(
            targets = targets,
            name = "%ssymv_u_kernel" % precision.prefix,
            src = "kernel/arm/symv_U.c",
            defines = precision.kernel_defines,
            symbol = "%ssymv_U" % precision.prefix,
        )
        _openblas_object(
            targets = targets,
            name = "%ssymv_l_kernel" % precision.prefix,
            src = "kernel/arm/symv_L.c",
            defines = precision.kernel_defines,
            symbol = "%ssymv_L" % precision.prefix,
        )
        _openblas_object(
            targets = targets,
            name = "cblas_%strmv" % precision.prefix,
            src = "interface/trmv.c",
            defines = ["CBLAS"] + precision.c_type_defines,
            symbol = "cblas_%strmv" % precision.prefix,
        )
        for trmv_variant in [
            struct(name = "NUU", src = "driver/level2/trmv_U.c", defines = ["UNIT"]),
            struct(name = "NUN", src = "driver/level2/trmv_U.c", defines = []),
            struct(name = "NLU", src = "driver/level2/trmv_L.c", defines = ["UNIT"]),
            struct(name = "NLN", src = "driver/level2/trmv_L.c", defines = []),
            struct(name = "TUU", src = "driver/level2/trmv_L.c", defines = ["TRANSA", "UNIT"]),
            struct(name = "TUN", src = "driver/level2/trmv_L.c", defines = ["TRANSA"]),
            struct(name = "TLU", src = "driver/level2/trmv_U.c", defines = ["TRANSA", "UNIT"]),
            struct(name = "TLN", src = "driver/level2/trmv_U.c", defines = ["TRANSA"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%strmv_%s" % (precision.prefix, trmv_variant.name.lower()),
                src = trmv_variant.src,
                defines = precision.kernel_defines + trmv_variant.defines,
                symbol = "%strmv_%s" % (precision.prefix, trmv_variant.name),
            )
        _openblas_object(
            targets = targets,
            name = "cblas_%strsv" % precision.prefix,
            src = "interface/trsv.c",
            defines = ["CBLAS"] + precision.c_type_defines,
            symbol = "cblas_%strsv" % precision.prefix,
        )
        for trsv_variant in [
            struct(name = "NUU", src = "driver/level2/trsv_U.c", defines = ["UNIT"]),
            struct(name = "NUN", src = "driver/level2/trsv_U.c", defines = []),
            struct(name = "NLU", src = "driver/level2/trsv_L.c", defines = ["UNIT"]),
            struct(name = "NLN", src = "driver/level2/trsv_L.c", defines = []),
            struct(name = "TUU", src = "driver/level2/trsv_L.c", defines = ["TRANSA", "UNIT"]),
            struct(name = "TUN", src = "driver/level2/trsv_L.c", defines = ["TRANSA"]),
            struct(name = "TLU", src = "driver/level2/trsv_U.c", defines = ["TRANSA", "UNIT"]),
            struct(name = "TLN", src = "driver/level2/trsv_U.c", defines = ["TRANSA"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%strsv_%s" % (precision.prefix, trsv_variant.name.lower()),
                src = trsv_variant.src,
                defines = precision.kernel_defines + trsv_variant.defines,
                symbol = "%strsv_%s" % (precision.prefix, trsv_variant.name),
            )
        _openblas_object(
            targets = targets,
            name = "cblas_%stpmv" % precision.prefix,
            src = "interface/tpmv.c",
            defines = ["CBLAS"] + precision.c_type_defines,
            symbol = "cblas_%stpmv" % precision.prefix,
        )
        for tpmv_variant in [
            struct(name = "NUU", src = "driver/level2/tpmv_U.c", defines = ["UNIT"]),
            struct(name = "NUN", src = "driver/level2/tpmv_U.c", defines = []),
            struct(name = "NLU", src = "driver/level2/tpmv_L.c", defines = ["UNIT"]),
            struct(name = "NLN", src = "driver/level2/tpmv_L.c", defines = []),
            struct(name = "TUU", src = "driver/level2/tpmv_L.c", defines = ["TRANSA", "UNIT"]),
            struct(name = "TUN", src = "driver/level2/tpmv_L.c", defines = ["TRANSA"]),
            struct(name = "TLU", src = "driver/level2/tpmv_U.c", defines = ["TRANSA", "UNIT"]),
            struct(name = "TLN", src = "driver/level2/tpmv_U.c", defines = ["TRANSA"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%stpmv_%s" % (precision.prefix, tpmv_variant.name.lower()),
                src = tpmv_variant.src,
                defines = precision.kernel_defines + tpmv_variant.defines,
                symbol = "%stpmv_%s" % (precision.prefix, tpmv_variant.name),
            )
        _openblas_object(
            targets = targets,
            name = "cblas_%stpsv" % precision.prefix,
            src = "interface/tpsv.c",
            defines = ["CBLAS"] + precision.c_type_defines,
            symbol = "cblas_%stpsv" % precision.prefix,
        )
        for tpsv_variant in [
            struct(name = "NUU", src = "driver/level2/tpsv_U.c", defines = ["UNIT"]),
            struct(name = "NUN", src = "driver/level2/tpsv_U.c", defines = []),
            struct(name = "NLU", src = "driver/level2/tpsv_L.c", defines = ["UNIT"]),
            struct(name = "NLN", src = "driver/level2/tpsv_L.c", defines = []),
            struct(name = "TUU", src = "driver/level2/tpsv_L.c", defines = ["TRANSA", "UNIT"]),
            struct(name = "TUN", src = "driver/level2/tpsv_L.c", defines = ["TRANSA"]),
            struct(name = "TLU", src = "driver/level2/tpsv_U.c", defines = ["TRANSA", "UNIT"]),
            struct(name = "TLN", src = "driver/level2/tpsv_U.c", defines = ["TRANSA"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%stpsv_%s" % (precision.prefix, tpsv_variant.name.lower()),
                src = tpsv_variant.src,
                defines = precision.kernel_defines + tpsv_variant.defines,
                symbol = "%stpsv_%s" % (precision.prefix, tpsv_variant.name),
            )
        for symmetric_update in [
            struct(name = "syr", src = "interface/syr.c", kernel_src = "driver/level2/syr_k.c"),
            struct(name = "syr2", src = "interface/syr2.c", kernel_src = "driver/level2/syr2_k.c"),
            struct(name = "spr", src = "interface/spr.c", kernel_src = "driver/level2/spr_k.c"),
            struct(name = "spr2", src = "interface/spr2.c", kernel_src = "driver/level2/spr2_k.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s" % (precision.prefix, symmetric_update.name),
                src = symmetric_update.src,
                defines = ["CBLAS"] + precision.c_type_defines,
                symbol = "cblas_%s%s" % (precision.prefix, symmetric_update.name),
            )
            for uplo_variant in [
                struct(suffix = "u", symbol_suffix = "U", defines = []),
                struct(suffix = "l", symbol_suffix = "L", defines = ["LOWER"]),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_%s" % (precision.prefix, symmetric_update.name, uplo_variant.suffix),
                    src = symmetric_update.kernel_src,
                    defines = precision.kernel_defines + uplo_variant.defines,
                    symbol = "%s%s_%s" % (precision.prefix, symmetric_update.name, uplo_variant.symbol_suffix),
                )
        _openblas_object(
            targets = targets,
            name = "cblas_%sgbmv" % precision.prefix,
            src = "interface/gbmv.c",
            defines = ["CBLAS"] + precision.c_type_defines,
            symbol = "cblas_%sgbmv" % precision.prefix,
        )
        for trans_variant in [
            struct(suffix = "n", symbol_suffix = "n", defines = []),
            struct(suffix = "t", symbol_suffix = "t", defines = ["TRANS"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%sgbmv_%s" % (precision.prefix, trans_variant.suffix),
                src = "driver/level2/gbmv_k.c",
                defines = precision.kernel_defines + trans_variant.defines,
                symbol = "%sgbmv_%s" % (precision.prefix, trans_variant.symbol_suffix),
            )
        for symmetric_mv in [
            struct(name = "sbmv", src = "interface/sbmv.c", kernel_src = "driver/level2/sbmv_k.c"),
            struct(name = "spmv", src = "interface/spmv.c", kernel_src = "driver/level2/spmv_k.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s" % (precision.prefix, symmetric_mv.name),
                src = symmetric_mv.src,
                defines = ["CBLAS"] + precision.c_type_defines,
                symbol = "cblas_%s%s" % (precision.prefix, symmetric_mv.name),
            )
            for uplo_variant in [
                struct(suffix = "u", symbol_suffix = "U", defines = []),
                struct(suffix = "l", symbol_suffix = "L", defines = ["LOWER"]),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_%s" % (precision.prefix, symmetric_mv.name, uplo_variant.suffix),
                    src = symmetric_mv.kernel_src,
                    defines = precision.kernel_defines + uplo_variant.defines,
                    symbol = "%s%s_%s" % (precision.prefix, symmetric_mv.name, uplo_variant.symbol_suffix),
                )
        for triangular_band in [
            struct(name = "tbmv", src = "interface/tbmv.c", upper_src = "driver/level2/tbmv_U.c", lower_src = "driver/level2/tbmv_L.c"),
            struct(name = "tbsv", src = "interface/tbsv.c", upper_src = "driver/level2/tbsv_U.c", lower_src = "driver/level2/tbsv_L.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s" % (precision.prefix, triangular_band.name),
                src = triangular_band.src,
                defines = ["CBLAS"] + precision.c_type_defines,
                symbol = "cblas_%s%s" % (precision.prefix, triangular_band.name),
            )
            for tb_variant in [
                struct(name = "NUU", src = triangular_band.upper_src, defines = ["UNIT"]),
                struct(name = "NUN", src = triangular_band.upper_src, defines = []),
                struct(name = "NLU", src = triangular_band.lower_src, defines = ["UNIT"]),
                struct(name = "NLN", src = triangular_band.lower_src, defines = []),
                struct(name = "TUU", src = triangular_band.lower_src, defines = ["TRANSA", "UNIT"]),
                struct(name = "TUN", src = triangular_band.lower_src, defines = ["TRANSA"]),
                struct(name = "TLU", src = triangular_band.upper_src, defines = ["TRANSA", "UNIT"]),
                struct(name = "TLN", src = triangular_band.upper_src, defines = ["TRANSA"]),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_%s" % (precision.prefix, triangular_band.name, tb_variant.name.lower()),
                    src = tb_variant.src,
                    defines = precision.kernel_defines + tb_variant.defines,
                    symbol = "%s%s_%s" % (precision.prefix, triangular_band.name, tb_variant.name),
                )

        for lapack_interface in [
            struct(name = "getf2", src = "interface/lapack/getf2.c"),
            struct(name = "getrf", src = "interface/lapack/getrf.c"),
            struct(name = "getrs", src = "interface/lapack/getrs.c"),
            struct(name = "gesv", src = "interface/lapack/gesv.c"),
            struct(name = "lauu2", src = "interface/lapack/lauu2.c"),
            struct(name = "lauum", src = "interface/lapack/lauum.c"),
            struct(name = "laswp", src = "interface/lapack/laswp.c"),
            struct(name = "potri", src = "interface/lapack/potri.c"),
            struct(name = "potf2", src = "interface/lapack/potf2.c"),
            struct(name = "potrf", src = "interface/lapack/potrf.c"),
            struct(name = "trti2", src = "interface/lapack/trti2.c"),
            struct(name = "trtri", src = "interface/lapack/trtri.c"),
            struct(name = "trtrs", src = "interface/lapack/trtrs.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "%s%s" % (precision.prefix, lapack_interface.name),
                src = lapack_interface.src,
                defines = precision.c_type_defines,
                symbol = "%s%s" % (precision.prefix, lapack_interface.name),
            )

        _openblas_object(
            targets = targets,
            name = "%sgetf2_k" % precision.prefix,
            src = "lapack/getf2/getf2_k.c",
            defines = precision.kernel_defines,
            symbol = "%sgetf2_k" % precision.prefix,
        )
        _openblas_object(
            targets = targets,
            name = "%sgetrf_single" % precision.prefix,
            src = "lapack/getrf/getrf_single.c",
            defines = precision.kernel_defines + ["UNIT"],
            symbol = "%sgetrf_single" % precision.prefix,
        )
        for trans_variant in [
            struct(suffix = "N", defines = []),
            struct(suffix = "T", defines = ["TRANS"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%sgetrs_%s_single" % (precision.prefix, trans_variant.suffix.lower()),
                src = "lapack/getrs/getrs_single.c",
                defines = precision.kernel_defines + trans_variant.defines,
                symbol = "%sgetrs_%s_single" % (precision.prefix, trans_variant.suffix),
            )
        for laswp_variant in [
            struct(name = "plus", defines = []),
            struct(name = "minus", defines = ["MINUS"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%slaswp_%s" % (precision.prefix, laswp_variant.name),
                src = "lapack/laswp/generic/laswp_k.c",
                defines = precision.kernel_defines + laswp_variant.defines,
                symbol = "%slaswp_%s" % (precision.prefix, laswp_variant.name),
            )
        for potf2_variant in [
            struct(suffix = "U", src = "lapack/potf2/potf2_U.c"),
            struct(suffix = "L", src = "lapack/potf2/potf2_L.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "%spotf2_%s" % (precision.prefix, potf2_variant.suffix.lower()),
                src = potf2_variant.src,
                defines = precision.kernel_defines,
                symbol = "%spotf2_%s" % (precision.prefix, potf2_variant.suffix),
            )
        for potrf_variant in [
            struct(suffix = "U", src = "lapack/potrf/potrf_U_single.c"),
            struct(suffix = "L", src = "lapack/potrf/potrf_L_single.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "%spotrf_%s_single" % (precision.prefix, potrf_variant.suffix.lower()),
                src = potrf_variant.src,
                defines = precision.kernel_defines,
                symbol = "%spotrf_%s_single" % (precision.prefix, potrf_variant.suffix),
            )
        for lauu2_variant in [
            struct(suffix = "U", src = "lapack/lauu2/lauu2_U.c"),
            struct(suffix = "L", src = "lapack/lauu2/lauu2_L.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "%slauu2_%s" % (precision.prefix, lauu2_variant.suffix.lower()),
                src = lauu2_variant.src,
                defines = precision.kernel_defines,
                symbol = "%slauu2_%s" % (precision.prefix, lauu2_variant.suffix),
            )
        for lauum_variant in [
            struct(suffix = "U", src = "lapack/lauum/lauum_U_single.c"),
            struct(suffix = "L", src = "lapack/lauum/lauum_L_single.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "%slauum_%s_single" % (precision.prefix, lauum_variant.suffix.lower()),
                src = lauum_variant.src,
                defines = precision.kernel_defines,
                symbol = "%slauum_%s_single" % (precision.prefix, lauum_variant.suffix),
            )
        for trti2_variant in [
            struct(suffix = "UU", src = "lapack/trti2/trti2_U.c", defines = ["UNIT"]),
            struct(suffix = "UN", src = "lapack/trti2/trti2_U.c", defines = []),
            struct(suffix = "LU", src = "lapack/trti2/trti2_L.c", defines = ["UNIT"]),
            struct(suffix = "LN", src = "lapack/trti2/trti2_L.c", defines = []),
        ]:
            _openblas_object(
                targets = targets,
                name = "%strti2_%s" % (precision.prefix, trti2_variant.suffix.lower()),
                src = trti2_variant.src,
                defines = precision.kernel_defines + trti2_variant.defines,
                symbol = "%strti2_%s" % (precision.prefix, trti2_variant.suffix),
            )
        for trtri_variant in [
            struct(suffix = "UU", src = "lapack/trtri/trtri_U_single.c", defines = ["UNIT"]),
            struct(suffix = "UN", src = "lapack/trtri/trtri_U_single.c", defines = []),
            struct(suffix = "LU", src = "lapack/trtri/trtri_L_single.c", defines = ["UNIT"]),
            struct(suffix = "LN", src = "lapack/trtri/trtri_L_single.c", defines = []),
        ]:
            _openblas_object(
                targets = targets,
                name = "%strtri_%s_single" % (precision.prefix, trtri_variant.suffix.lower()),
                src = trtri_variant.src,
                defines = precision.kernel_defines + trtri_variant.defines,
                symbol = "%strtri_%s_single" % (precision.prefix, trtri_variant.suffix),
            )
        for trtrs_variant in [
            struct(suffix = "UNU", defines = []),
            struct(suffix = "UNN", defines = ["DIAG"]),
            struct(suffix = "UTU", defines = ["TRANS"]),
            struct(suffix = "UTN", defines = ["TRANS", "DIAG"]),
            struct(suffix = "LNU", defines = ["UPLO"]),
            struct(suffix = "LNN", defines = ["UPLO", "DIAG"]),
            struct(suffix = "LTU", defines = ["UPLO", "TRANS"]),
            struct(suffix = "LTN", defines = ["UPLO", "TRANS", "DIAG"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%strtrs_%s_single" % (precision.prefix, trtrs_variant.suffix.lower()),
                src = "lapack/trtrs/trtrs_single.c",
                defines = precision.kernel_defines + trtrs_variant.defines,
                symbol = "%strtrs_%s_single" % (precision.prefix, trtrs_variant.suffix),
            )
        _add_netlib_getri(targets, precision)

    for precision in [
        struct(prefix = "c", real_prefix = "s", index_prefix = "ic", c_type_defines = ["COMPLEX"], kernel_defines = ["COMPLEX"]),
        struct(prefix = "z", real_prefix = "d", index_prefix = "iz", c_type_defines = ["COMPLEX", "DOUBLE"], kernel_defines = ["COMPLEX", "DOUBLE"]),
    ]:
        for op in [
            struct(name = "axpy", src = "interface/zaxpy.c", kernel_src = "kernel/x86_64/zaxpy.c", extra_defines = []),
            struct(name = "axpyc", src = "interface/zaxpy.c", kernel_src = "kernel/x86_64/zaxpy.c", extra_defines = ["CONJ"]),
            struct(name = "copy", src = "interface/copy.c", kernel_src = "kernel/arm/zcopy.c", extra_defines = []),
            struct(name = "swap", src = "interface/zswap.c", kernel_src = "kernel/arm/zswap.c", extra_defines = []),
            struct(name = "scal", src = "interface/zscal.c", kernel_src = "kernel/x86_64/zscal.c", extra_defines = []),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s" % (precision.prefix, op.name),
                src = op.src,
                defines = ["CBLAS"] + precision.c_type_defines + op.extra_defines,
                symbol = "cblas_%s%s" % (precision.prefix, op.name),
            )
            _openblas_object(
                targets = targets,
                name = "%s%s_kernel" % (precision.prefix, op.name),
                src = op.kernel_src,
                defines = precision.kernel_defines + op.extra_defines,
                symbol = "%s%s_k" % (precision.prefix, op.name),
            )
        _openblas_object(
            targets = targets,
            name = "%sswap" % precision.prefix,
            src = "interface/zswap.c",
            defines = precision.c_type_defines,
            symbol = "%sswap" % precision.prefix,
        )

        _openblas_object(
            targets = targets,
            name = "cblas_%s%sscal" % (precision.prefix, precision.real_prefix),
            src = "interface/zscal.c",
            defines = ["CBLAS", "SSCAL"] + precision.c_type_defines,
            symbol = "cblas_%s%sscal" % (precision.prefix, precision.real_prefix),
        )

        for dot in [
            struct(name = "dotu", extra_defines = []),
            struct(name = "dotc", extra_defines = ["CONJ"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s" % (precision.prefix, dot.name),
                src = "interface/zdot.c",
                defines = ["CBLAS"] + precision.c_type_defines + dot.extra_defines,
                symbol = "cblas_%s%s" % (precision.prefix, dot.name),
            )
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s_sub" % (precision.prefix, dot.name),
                src = "interface/zdot.c",
                defines = ["CBLAS", "FORCE_USE_STACK"] + precision.c_type_defines + dot.extra_defines,
                symbol = "cblas_%s%s_sub" % (precision.prefix, dot.name),
            )
            _openblas_object(
                targets = targets,
                name = "%s%s_kernel" % (precision.prefix, dot.name),
                src = "kernel/x86_64/zdot.c",
                defines = precision.kernel_defines + dot.extra_defines,
                symbol = "%s%s_k" % (precision.prefix, dot.name),
            )

        for reduction in [
            struct(name = "asum", src = "interface/asum.c", kernel_src = "kernel/x86_64/zasum.c"),
            struct(name = "nrm2", src = "interface/nrm2.c", kernel_src = "kernel/arm/znrm2.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s%s" % (precision.real_prefix, precision.prefix, reduction.name),
                src = reduction.src,
                defines = ["CBLAS"] + precision.c_type_defines,
                symbol = "cblas_%s%s%s" % (precision.real_prefix, precision.prefix, reduction.name),
            )
            _openblas_object(
                targets = targets,
                name = "%s%s%s_kernel" % (precision.real_prefix, precision.prefix, reduction.name),
                src = reduction.kernel_src,
                defines = precision.kernel_defines,
                symbol = "%s%s_k" % (precision.prefix, reduction.name),
            )

        _openblas_object(
            targets = targets,
            name = "cblas_%samax" % precision.index_prefix,
            src = "interface/imax.c",
            defines = ["CBLAS", "USE_ABS"] + precision.c_type_defines,
            symbol = "cblas_%samax" % precision.index_prefix,
        )
        _openblas_object(
            targets = targets,
            name = "%samax_kernel" % precision.index_prefix,
            src = "kernel/arm/izamax.c",
            defines = precision.kernel_defines,
            symbol = "%samax_k" % precision.index_prefix,
        )
        for amin_op in [
            struct(name = "amin", src = "kernel/arm/zamin.c", symbol = "%samin_k" % precision.prefix),
            struct(name = "iamin", src = "kernel/arm/izamin.c", symbol = "i%samin_k" % precision.prefix),
        ]:
            _openblas_object(
                targets = targets,
                name = "%s%s_kernel" % (precision.prefix, amin_op.name),
                src = amin_op.src,
                defines = precision.kernel_defines,
                symbol = amin_op.symbol,
            )

        for complex_lapack_interface in [
            struct(name = "getf2", src = "interface/lapack/zgetf2.c"),
            struct(name = "getrf", src = "interface/lapack/zgetrf.c"),
            struct(name = "getrs", src = "interface/lapack/zgetrs.c"),
            struct(name = "gesv", src = "interface/lapack/gesv.c"),
            struct(name = "lauu2", src = "interface/lapack/zlauu2.c"),
            struct(name = "lauum", src = "interface/lapack/zlauum.c"),
            struct(name = "laswp", src = "interface/lapack/zlaswp.c"),
            struct(name = "potri", src = "interface/lapack/potri.c"),
            struct(name = "potf2", src = "interface/lapack/zpotf2.c"),
            struct(name = "potrf", src = "interface/lapack/zpotrf.c"),
            struct(name = "trti2", src = "interface/lapack/ztrti2.c"),
            struct(name = "trtri", src = "interface/lapack/ztrtri.c"),
            struct(name = "trtrs", src = "interface/lapack/ztrtrs.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "%s%s" % (precision.prefix, complex_lapack_interface.name),
                src = complex_lapack_interface.src,
                defines = precision.c_type_defines,
                symbol = "%s%s" % (precision.prefix, complex_lapack_interface.name),
            )

        _openblas_object(
            targets = targets,
            name = "%sgetf2_k" % precision.prefix,
            src = "lapack/getf2/zgetf2_k.c",
            defines = precision.kernel_defines,
            symbol = "%sgetf2_k" % precision.prefix,
        )
        _openblas_object(
            targets = targets,
            name = "%sgetrf_single" % precision.prefix,
            src = "lapack/getrf/getrf_single.c",
            defines = precision.kernel_defines + ["UNIT"],
            symbol = "%sgetrf_single" % precision.prefix,
        )
        for trans_variant in [
            struct(suffix = "N", defines = ["TRANS=1"]),
            struct(suffix = "T", defines = ["TRANS=2"]),
            struct(suffix = "R", defines = ["TRANS=3"]),
            struct(suffix = "C", defines = ["TRANS=4"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%sgetrs_%s_single" % (precision.prefix, trans_variant.suffix.lower()),
                src = "lapack/getrs/zgetrs_single.c",
                defines = precision.kernel_defines + trans_variant.defines,
                symbol = "%sgetrs_%s_single" % (precision.prefix, trans_variant.suffix),
            )
        for laswp_variant in [
            struct(name = "plus", defines = []),
            struct(name = "minus", defines = ["MINUS"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%slaswp_%s" % (precision.prefix, laswp_variant.name),
                src = "lapack/laswp/generic/zlaswp_k.c",
                defines = precision.kernel_defines + laswp_variant.defines,
                symbol = "%slaswp_%s" % (precision.prefix, laswp_variant.name),
            )
        for potf2_variant in [
            struct(suffix = "U", src = "lapack/potf2/zpotf2_U.c"),
            struct(suffix = "L", src = "lapack/potf2/zpotf2_L.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "%spotf2_%s" % (precision.prefix, potf2_variant.suffix.lower()),
                src = potf2_variant.src,
                defines = precision.kernel_defines,
                symbol = "%spotf2_%s" % (precision.prefix, potf2_variant.suffix),
            )
        for potrf_variant in [
            struct(suffix = "U", src = "lapack/potrf/potrf_U_single.c"),
            struct(suffix = "L", src = "lapack/potrf/potrf_L_single.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "%spotrf_%s_single" % (precision.prefix, potrf_variant.suffix.lower()),
                src = potrf_variant.src,
                defines = precision.kernel_defines,
                symbol = "%spotrf_%s_single" % (precision.prefix, potrf_variant.suffix),
            )
        for lauu2_variant in [
            struct(suffix = "U", src = "lapack/lauu2/zlauu2_U.c"),
            struct(suffix = "L", src = "lapack/lauu2/zlauu2_L.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "%slauu2_%s" % (precision.prefix, lauu2_variant.suffix.lower()),
                src = lauu2_variant.src,
                defines = precision.kernel_defines,
                symbol = "%slauu2_%s" % (precision.prefix, lauu2_variant.suffix),
            )
        for lauum_variant in [
            struct(suffix = "U", src = "lapack/lauum/lauum_U_single.c"),
            struct(suffix = "L", src = "lapack/lauum/lauum_L_single.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "%slauum_%s_single" % (precision.prefix, lauum_variant.suffix.lower()),
                src = lauum_variant.src,
                defines = precision.kernel_defines,
                symbol = "%slauum_%s_single" % (precision.prefix, lauum_variant.suffix),
            )
        for trti2_variant in [
            struct(suffix = "UU", src = "lapack/trti2/ztrti2_U.c", defines = ["UNIT"]),
            struct(suffix = "UN", src = "lapack/trti2/ztrti2_U.c", defines = []),
            struct(suffix = "LU", src = "lapack/trti2/ztrti2_L.c", defines = ["UNIT"]),
            struct(suffix = "LN", src = "lapack/trti2/ztrti2_L.c", defines = []),
        ]:
            _openblas_object(
                targets = targets,
                name = "%strti2_%s" % (precision.prefix, trti2_variant.suffix.lower()),
                src = trti2_variant.src,
                defines = precision.kernel_defines + trti2_variant.defines,
                symbol = "%strti2_%s" % (precision.prefix, trti2_variant.suffix),
            )
        for trtri_variant in [
            struct(suffix = "UU", src = "lapack/trtri/trtri_U_single.c", defines = ["UNIT"]),
            struct(suffix = "UN", src = "lapack/trtri/trtri_U_single.c", defines = []),
            struct(suffix = "LU", src = "lapack/trtri/trtri_L_single.c", defines = ["UNIT"]),
            struct(suffix = "LN", src = "lapack/trtri/trtri_L_single.c", defines = []),
        ]:
            _openblas_object(
                targets = targets,
                name = "%strtri_%s_single" % (precision.prefix, trtri_variant.suffix.lower()),
                src = trtri_variant.src,
                defines = precision.kernel_defines + trtri_variant.defines,
                symbol = "%strtri_%s_single" % (precision.prefix, trtri_variant.suffix),
            )
        for trtrs_variant in [
            struct(suffix = "UNU", defines = ["TRANS=1"]),
            struct(suffix = "UNN", defines = ["TRANS=1", "DIAG"]),
            struct(suffix = "UTU", defines = ["TRANS=2"]),
            struct(suffix = "UTN", defines = ["TRANS=2", "DIAG"]),
            struct(suffix = "URU", defines = ["TRANS=3"]),
            struct(suffix = "URN", defines = ["TRANS=3", "DIAG"]),
            struct(suffix = "UCU", defines = ["TRANS=4"]),
            struct(suffix = "UCN", defines = ["TRANS=4", "DIAG"]),
            struct(suffix = "LNU", defines = ["UPLO", "TRANS=1"]),
            struct(suffix = "LNN", defines = ["UPLO", "TRANS=1", "DIAG"]),
            struct(suffix = "LTU", defines = ["UPLO", "TRANS=2"]),
            struct(suffix = "LTN", defines = ["UPLO", "TRANS=2", "DIAG"]),
            struct(suffix = "LRU", defines = ["UPLO", "TRANS=3"]),
            struct(suffix = "LRN", defines = ["UPLO", "TRANS=3", "DIAG"]),
            struct(suffix = "LCU", defines = ["UPLO", "TRANS=4"]),
            struct(suffix = "LCN", defines = ["UPLO", "TRANS=4", "DIAG"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%strtrs_%s_single" % (precision.prefix, trtrs_variant.suffix.lower()),
                src = "lapack/trtrs/ztrtrs_single.c",
                defines = precision.kernel_defines + trtrs_variant.defines,
                symbol = "%strtrs_%s_single" % (precision.prefix, trtrs_variant.suffix),
            )
        _add_netlib_getri(targets, precision)

        _openblas_object(
            targets = targets,
            name = "cblas_%sgemv" % precision.prefix,
            src = "interface/zgemv.c",
            defines = ["CBLAS"] + precision.c_type_defines,
            symbol = "cblas_%sgemv" % precision.prefix,
        )
        _openblas_object(
            targets = targets,
            name = "%sgemv" % precision.prefix,
            src = "interface/zgemv.c",
            defines = precision.c_type_defines,
            symbol = "%sgemv" % precision.prefix,
        )
        for gemv_variant in [
            struct(suffix = "n", src = "kernel/arm/zgemv_n.c", defines = []),
            struct(suffix = "t", src = "kernel/arm/zgemv_t.c", defines = ["TRANS"]),
            struct(suffix = "r", src = "kernel/arm/zgemv_n.c", defines = ["CONJ"]),
            struct(suffix = "c", src = "kernel/arm/zgemv_t.c", defines = ["TRANS", "CONJ"]),
            struct(suffix = "o", src = "kernel/arm/zgemv_n.c", defines = ["XCONJ"]),
            struct(suffix = "u", src = "kernel/arm/zgemv_t.c", defines = ["TRANS", "XCONJ"]),
            struct(suffix = "s", src = "kernel/arm/zgemv_n.c", defines = ["CONJ", "XCONJ"]),
            struct(suffix = "d", src = "kernel/arm/zgemv_t.c", defines = ["TRANS", "CONJ", "XCONJ"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%sgemv_%s" % (precision.prefix, gemv_variant.suffix),
                src = gemv_variant.src,
                defines = precision.kernel_defines + gemv_variant.defines,
                symbol = "%sgemv_%s" % (precision.prefix, gemv_variant.suffix),
            )

        for ger_variant in [
            struct(name = "geru", defines = []),
            struct(name = "gerc", defines = ["CONJ"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s" % (precision.prefix, ger_variant.name),
                src = "interface/zger.c",
                defines = ["CBLAS"] + precision.c_type_defines + ger_variant.defines,
                symbol = "cblas_%s%s" % (precision.prefix, ger_variant.name),
            )
            _openblas_object(
                targets = targets,
                name = "%s%s_kernel" % (precision.prefix, ger_variant.name),
                src = "kernel/generic/zger.c",
                defines = precision.kernel_defines + ger_variant.defines,
                symbol = "%s%s_k" % (precision.prefix, ger_variant.name),
            )
        _openblas_object(
            targets = targets,
            name = "%sgerv_kernel" % precision.prefix,
            src = "kernel/generic/zger.c",
            defines = precision.kernel_defines + ["XCONJ"],
            symbol = "%sgerv_k" % precision.prefix,
        )

        for triangular_level2 in [
            struct(name = "trmv", interface_src = "interface/ztrmv.c", upper_src = "driver/level2/ztrmv_U.c", lower_src = "driver/level2/ztrmv_L.c"),
            struct(name = "trsv", interface_src = "interface/ztrsv.c", upper_src = "driver/level2/ztrsv_U.c", lower_src = "driver/level2/ztrsv_L.c"),
            struct(name = "tpmv", interface_src = "interface/ztpmv.c", upper_src = "driver/level2/ztpmv_U.c", lower_src = "driver/level2/ztpmv_L.c"),
            struct(name = "tpsv", interface_src = "interface/ztpsv.c", upper_src = "driver/level2/ztpsv_U.c", lower_src = "driver/level2/ztpsv_L.c"),
            struct(name = "tbmv", interface_src = "interface/ztbmv.c", upper_src = "driver/level2/ztbmv_U.c", lower_src = "driver/level2/ztbmv_L.c"),
            struct(name = "tbsv", interface_src = "interface/ztbsv.c", upper_src = "driver/level2/ztbsv_U.c", lower_src = "driver/level2/ztbsv_L.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s" % (precision.prefix, triangular_level2.name),
                src = triangular_level2.interface_src,
                defines = ["CBLAS"] + precision.c_type_defines,
                symbol = "cblas_%s%s" % (precision.prefix, triangular_level2.name),
            )
            for tri_variant in [
                struct(name = "NUU", src = triangular_level2.upper_src, defines = ["TRANSA=1", "UNIT"]),
                struct(name = "NUN", src = triangular_level2.upper_src, defines = ["TRANSA=1"]),
                struct(name = "NLU", src = triangular_level2.lower_src, defines = ["TRANSA=1", "UNIT"]),
                struct(name = "NLN", src = triangular_level2.lower_src, defines = ["TRANSA=1"]),
                struct(name = "TUU", src = triangular_level2.lower_src, defines = ["TRANSA=2", "UNIT"]),
                struct(name = "TUN", src = triangular_level2.lower_src, defines = ["TRANSA=2"]),
                struct(name = "TLU", src = triangular_level2.upper_src, defines = ["TRANSA=2", "UNIT"]),
                struct(name = "TLN", src = triangular_level2.upper_src, defines = ["TRANSA=2"]),
                struct(name = "RUU", src = triangular_level2.upper_src, defines = ["TRANSA=3", "UNIT"]),
                struct(name = "RUN", src = triangular_level2.upper_src, defines = ["TRANSA=3"]),
                struct(name = "RLU", src = triangular_level2.lower_src, defines = ["TRANSA=3", "UNIT"]),
                struct(name = "RLN", src = triangular_level2.lower_src, defines = ["TRANSA=3"]),
                struct(name = "CUU", src = triangular_level2.lower_src, defines = ["TRANSA=4", "UNIT"]),
                struct(name = "CUN", src = triangular_level2.lower_src, defines = ["TRANSA=4"]),
                struct(name = "CLU", src = triangular_level2.upper_src, defines = ["TRANSA=4", "UNIT"]),
                struct(name = "CLN", src = triangular_level2.upper_src, defines = ["TRANSA=4"]),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_%s" % (precision.prefix, triangular_level2.name, tri_variant.name.lower()),
                    src = tri_variant.src,
                    defines = precision.kernel_defines + tri_variant.defines,
                    symbol = "%s%s_%s" % (precision.prefix, triangular_level2.name, tri_variant.name),
                )

        _openblas_object(
            targets = targets,
            name = "cblas_%sgbmv" % precision.prefix,
            src = "interface/zgbmv.c",
            defines = ["CBLAS"] + precision.c_type_defines,
            symbol = "cblas_%sgbmv" % precision.prefix,
        )
        for gbmv_variant in [
            struct(suffix = "n", defines = []),
            struct(suffix = "t", defines = ["TRANS"]),
            struct(suffix = "r", defines = ["CONJ"]),
            struct(suffix = "c", defines = ["TRANS", "CONJ"]),
            struct(suffix = "o", defines = ["XCONJ"]),
            struct(suffix = "u", defines = ["TRANS", "XCONJ"]),
            struct(suffix = "s", defines = ["CONJ", "XCONJ"]),
            struct(suffix = "d", defines = ["TRANS", "CONJ", "XCONJ"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%sgbmv_%s" % (precision.prefix, gbmv_variant.suffix),
                src = "driver/level2/zgbmv_k.c",
                defines = precision.kernel_defines + gbmv_variant.defines,
                symbol = "%sgbmv_%s" % (precision.prefix, gbmv_variant.suffix),
            )

        for hermitian_mv in [
            struct(name = "hemv", interface_src = "interface/zhemv.c", kernel_src = "kernel/generic/zhemv_k.c", extra_defines = ["HEMV"]),
            struct(name = "hbmv", interface_src = "interface/zhbmv.c", kernel_src = "driver/level2/zhbmv_k.c", extra_defines = []),
            struct(name = "hpmv", interface_src = "interface/zhpmv.c", kernel_src = "driver/level2/zhpmv_k.c", extra_defines = []),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s" % (precision.prefix, hermitian_mv.name),
                src = hermitian_mv.interface_src,
                defines = ["CBLAS"] + precision.c_type_defines,
                symbol = "cblas_%s%s" % (precision.prefix, hermitian_mv.name),
            )
            for uplo_variant in [
                struct(suffix = "U", defines = []),
                struct(suffix = "L", defines = ["LOWER"]),
                struct(suffix = "V", defines = ["HEMVREV"]),
                struct(suffix = "M", defines = ["LOWER", "HEMVREV"]),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_%s" % (precision.prefix, hermitian_mv.name, uplo_variant.suffix.lower()),
                    src = hermitian_mv.kernel_src,
                    defines = precision.kernel_defines + hermitian_mv.extra_defines + uplo_variant.defines,
                    symbol = "%s%s_%s" % (precision.prefix, hermitian_mv.name, uplo_variant.suffix),
                )

        no_complex_kernel_defines = [d for d in precision.kernel_defines if d == "DOUBLE"]
        for hermitian_rank in [
            struct(name = "her", interface_src = "interface/zher.c", kernel_src = "driver/level2/zher_k.c", use_complex_kernel = True),
            struct(name = "her2", interface_src = "interface/zher2.c", kernel_src = "driver/level2/zher2_k.c", use_complex_kernel = True),
            struct(name = "hpr", interface_src = "interface/zhpr.c", kernel_src = "driver/level2/zhpr_k.c", use_complex_kernel = True),
            struct(name = "hpr2", interface_src = "interface/zhpr2.c", kernel_src = "driver/level2/zhpr2_k.c", use_complex_kernel = True),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s" % (precision.prefix, hermitian_rank.name),
                src = hermitian_rank.interface_src,
                defines = ["CBLAS"] + precision.c_type_defines,
                symbol = "cblas_%s%s" % (precision.prefix, hermitian_rank.name),
            )
            rank_kernel_defines = precision.kernel_defines if hermitian_rank.use_complex_kernel else no_complex_kernel_defines
            for uplo_variant in [
                struct(suffix = "U", defines = []),
                struct(suffix = "L", defines = ["LOWER"]),
                struct(suffix = "V", defines = ["HEMVREV"]),
                struct(suffix = "M", defines = ["LOWER", "HEMVREV"]),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_%s" % (precision.prefix, hermitian_rank.name, uplo_variant.suffix.lower()),
                    src = hermitian_rank.kernel_src,
                    defines = rank_kernel_defines + uplo_variant.defines,
                    symbol = "%s%s_%s" % (precision.prefix, hermitian_rank.name, uplo_variant.suffix),
                )

        _openblas_object(
            targets = targets,
            name = "cblas_%sgemm" % precision.prefix,
            src = "interface/gemm.c",
            defines = ["CBLAS"] + precision.c_type_defines,
            symbol = "cblas_%sgemm" % precision.prefix,
        )
        _openblas_object(
            targets = targets,
            name = "%sgemm" % precision.prefix,
            src = "interface/gemm.c",
            defines = precision.c_type_defines,
            symbol = "%sgemm" % precision.prefix,
        )
        for gemm_variant in [
            struct(suffix = "nn", defines = ["NN"]),
            struct(suffix = "nt", defines = ["NT"]),
            struct(suffix = "nr", defines = ["NR"]),
            struct(suffix = "nc", defines = ["NC"]),
            struct(suffix = "tn", defines = ["TN"]),
            struct(suffix = "tt", defines = ["TT"]),
            struct(suffix = "tr", defines = ["TR"]),
            struct(suffix = "tc", defines = ["TC"]),
            struct(suffix = "rn", defines = ["RN"]),
            struct(suffix = "rt", defines = ["RT"]),
            struct(suffix = "rr", defines = ["RR"]),
            struct(suffix = "rc", defines = ["RC=RC"]),
            struct(suffix = "cn", defines = ["CN"]),
            struct(suffix = "ct", defines = ["CT"]),
            struct(suffix = "cr", defines = ["CR=CR"]),
            struct(suffix = "cc", defines = ["CC"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%sgemm_%s" % (precision.prefix, gemm_variant.suffix),
                src = "driver/level3/gemm.c",
                defines = precision.kernel_defines + gemm_variant.defines,
                symbol = "%sgemm_%s" % (precision.prefix, gemm_variant.suffix),
            )
        for gemm_kernel in [
            struct(name = "gemm_kernel_n", src = "kernel/generic/zgemmkernel_2x2.c", defines = ["NN"], symbol = "gemm_kernel_n"),
            struct(name = "gemm_kernel_l", src = "kernel/generic/zgemmkernel_2x2.c", defines = ["CN"], symbol = "gemm_kernel_l"),
            struct(name = "gemm_kernel_r", src = "kernel/generic/zgemmkernel_2x2.c", defines = ["NC"], symbol = "gemm_kernel_r"),
            struct(name = "gemm_kernel_b", src = "kernel/generic/zgemmkernel_2x2.c", defines = ["CC"], symbol = "gemm_kernel_b"),
            struct(name = "gemm_beta", src = "kernel/generic/zgemm_beta.c", defines = [], symbol = "gemm_beta"),
            struct(name = "gemm_oncopy", src = "kernel/generic/zgemm_ncopy_2.c", defines = [], symbol = "gemm_oncopy"),
            struct(name = "gemm_otcopy", src = "kernel/generic/zgemm_tcopy_2.c", defines = [], symbol = "gemm_otcopy"),
        ]:
            _openblas_object(
                targets = targets,
                name = "%s%s" % (precision.prefix, gemm_kernel.name),
                src = gemm_kernel.src,
                defines = precision.kernel_defines + gemm_kernel.defines,
                symbol = "%s%s" % (precision.prefix, gemm_kernel.symbol),
            )

        for complex_symm in [
            struct(name = "symm", interface_defines = [], driver_src = "driver/level3/symm_k.c", copy_prefix = "symm", copy_upper_src = "kernel/generic/zsymm_ucopy_2.c", copy_lower_src = "kernel/generic/zsymm_lcopy_2.c"),
            struct(name = "hemm", interface_defines = ["HEMM"], driver_src = "driver/level3/zhemm_k.c", copy_prefix = "hemm", copy_upper_src = "kernel/generic/zhemm_utcopy_2.c", copy_lower_src = "kernel/generic/zhemm_ltcopy_2.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s" % (precision.prefix, complex_symm.name),
                src = "interface/symm.c",
                defines = ["CBLAS"] + precision.c_type_defines + complex_symm.interface_defines,
                symbol = "cblas_%s%s" % (precision.prefix, complex_symm.name),
            )
            for symm_variant in [
                struct(name = "LU", defines = ["NN"]),
                struct(name = "LL", defines = ["LOWER", "NN"]),
                struct(name = "RU", defines = ["RSIDE", "NN" if complex_symm.name == "symm" else "NC"]),
                struct(name = "RL", defines = ["LOWER", "RSIDE", "NN" if complex_symm.name == "symm" else "NC"]),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_%s" % (precision.prefix, complex_symm.name, symm_variant.name.lower()),
                    src = complex_symm.driver_src,
                    defines = precision.kernel_defines + symm_variant.defines,
                    symbol = "%s%s_%s" % (precision.prefix, complex_symm.name, symm_variant.name),
                )
            for symm_copy in [
                struct(name = "outcopy", src = complex_symm.copy_upper_src, defines = ["OUTER"]),
                struct(name = "oltcopy", src = complex_symm.copy_lower_src, defines = ["OUTER", "LOWER"]),
                struct(name = "iutcopy", src = complex_symm.copy_upper_src, defines = []),
                struct(name = "iltcopy", src = complex_symm.copy_lower_src, defines = ["LOWER"]),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_%s" % (precision.prefix, complex_symm.copy_prefix, symm_copy.name),
                    src = symm_copy.src,
                    defines = precision.kernel_defines + symm_copy.defines,
                    symbol = "%s%s_%s" % (precision.prefix, complex_symm.copy_prefix, symm_copy.name),
                )

        for symmetric_rankk in [
            struct(name = "syrk", interface_src = "interface/syrk.c", driver_src = "driver/level3/syrk_k.c", kernel_src = "driver/level3/syrk_kernel.c"),
            struct(name = "syr2k", interface_src = "interface/syr2k.c", driver_src = "driver/level3/syr2k_k.c", kernel_src = "driver/level3/syr2k_kernel.c"),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s" % (precision.prefix, symmetric_rankk.name),
                src = symmetric_rankk.interface_src,
                defines = ["CBLAS"] + precision.c_type_defines,
                symbol = "cblas_%s%s" % (precision.prefix, symmetric_rankk.name),
            )
            for rankk_variant in [
                struct(name = "UN", defines = []),
                struct(name = "UT", defines = ["TRANS"]),
                struct(name = "LN", defines = ["LOWER"]),
                struct(name = "LT", defines = ["LOWER", "TRANS"]),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_%s" % (precision.prefix, symmetric_rankk.name, rankk_variant.name.lower()),
                    src = symmetric_rankk.driver_src,
                    defines = precision.kernel_defines + rankk_variant.defines,
                    symbol = "%s%s_%s" % (precision.prefix, symmetric_rankk.name, rankk_variant.name),
                )
            for uplo_variant in [
                struct(suffix = "u", symbol_suffix = "U", defines = []),
                struct(suffix = "l", symbol_suffix = "L", defines = ["LOWER"]),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_kernel_%s" % (precision.prefix, symmetric_rankk.name, uplo_variant.suffix),
                    src = symmetric_rankk.kernel_src,
                    defines = precision.kernel_defines + uplo_variant.defines,
                    symbol = "%s%s_kernel_%s" % (precision.prefix, symmetric_rankk.name, uplo_variant.symbol_suffix),
                )

        for hermitian_rankk in [
            struct(name = "herk", interface_src = "interface/syrk.c", driver_src = "driver/level3/zherk_k.c", kernel_src = "driver/level3/zherk_kernel.c", driver_defines = ["HERK"], kernel_defines = ["HERK"]),
            struct(name = "her2k", interface_src = "interface/syr2k.c", driver_src = "driver/level3/zher2k_k.c", kernel_src = "driver/level3/zher2k_kernel.c", driver_defines = ["HER2K"], kernel_defines = []),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s" % (precision.prefix, hermitian_rankk.name),
                src = hermitian_rankk.interface_src,
                defines = ["CBLAS", "HEMM"] + precision.c_type_defines,
                symbol = "cblas_%s%s" % (precision.prefix, hermitian_rankk.name),
            )
            for rankk_variant in [
                struct(name = "UN", defines = []),
                struct(name = "UC", defines = ["TRANS", "CONJ"]),
                struct(name = "LN", defines = ["LOWER"]),
                struct(name = "LC", defines = ["LOWER", "TRANS", "CONJ"]),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_%s" % (precision.prefix, hermitian_rankk.name, rankk_variant.name.lower()),
                    src = hermitian_rankk.driver_src,
                    defines = precision.kernel_defines + hermitian_rankk.driver_defines + rankk_variant.defines,
                    symbol = "%s%s_%s" % (precision.prefix, hermitian_rankk.name, rankk_variant.name),
                )
                _openblas_object(
                    targets = targets,
                    name = "%s%s_kernel_%s" % (precision.prefix, hermitian_rankk.name, rankk_variant.name.lower()),
                    src = hermitian_rankk.kernel_src,
                    defines = precision.kernel_defines + hermitian_rankk.kernel_defines + [d for d in rankk_variant.defines if d != "TRANS"],
                    symbol = "%s%s_kernel_%s" % (precision.prefix, hermitian_rankk.name, rankk_variant.name),
                )

        for triangular_level3 in [
            struct(name = "trmm", c_defines = ["CBLAS", "TRMM"], left_src = "driver/level3/trmm_L.c", right_src = "driver/level3/trmm_R.c", copy_prefix = "trmm", copy_src_prefix = "ztrmm"),
            struct(name = "trsm", c_defines = ["CBLAS"], left_src = "driver/level3/trsm_L.c", right_src = "driver/level3/trsm_R.c", copy_prefix = "trsm", copy_src_prefix = "ztrsm"),
        ]:
            _openblas_object(
                targets = targets,
                name = "cblas_%s%s" % (precision.prefix, triangular_level3.name),
                src = "interface/trsm.c",
                defines = triangular_level3.c_defines + precision.c_type_defines,
                symbol = "cblas_%s%s" % (precision.prefix, triangular_level3.name),
            )
            if triangular_level3.name == "trsm":
                _openblas_object(
                    targets = targets,
                    name = "%s%s" % (precision.prefix, triangular_level3.name),
                    src = "interface/trsm.c",
                    defines = precision.c_type_defines,
                    symbol = "%s%s" % (precision.prefix, triangular_level3.name),
                )
            for tri_variant in [
                struct(name = "LNUU", src = triangular_level3.left_src, defines = ["UPPER", "UNIT"]),
                struct(name = "LNUN", src = triangular_level3.left_src, defines = ["UPPER"]),
                struct(name = "LNLU", src = triangular_level3.left_src, defines = ["UNIT"]),
                struct(name = "LNLN", src = triangular_level3.left_src, defines = []),
                struct(name = "LTUU", src = triangular_level3.left_src, defines = ["TRANSA", "UPPER", "UNIT"]),
                struct(name = "LTUN", src = triangular_level3.left_src, defines = ["TRANSA", "UPPER"]),
                struct(name = "LTLU", src = triangular_level3.left_src, defines = ["TRANSA", "UNIT"]),
                struct(name = "LTLN", src = triangular_level3.left_src, defines = ["TRANSA"]),
                struct(name = "LRUU", src = triangular_level3.left_src, defines = ["CONJ", "UPPER", "UNIT"]),
                struct(name = "LRUN", src = triangular_level3.left_src, defines = ["CONJ", "UPPER"]),
                struct(name = "LRLU", src = triangular_level3.left_src, defines = ["CONJ", "UNIT"]),
                struct(name = "LRLN", src = triangular_level3.left_src, defines = ["CONJ"]),
                struct(name = "LCUU", src = triangular_level3.left_src, defines = ["TRANSA", "CONJ", "UPPER", "UNIT"]),
                struct(name = "LCUN", src = triangular_level3.left_src, defines = ["TRANSA", "CONJ", "UPPER"]),
                struct(name = "LCLU", src = triangular_level3.left_src, defines = ["TRANSA", "CONJ", "UNIT"]),
                struct(name = "LCLN", src = triangular_level3.left_src, defines = ["TRANSA", "CONJ"]),
                struct(name = "RNUU", src = triangular_level3.right_src, defines = ["UPPER", "UNIT"]),
                struct(name = "RNUN", src = triangular_level3.right_src, defines = ["UPPER"]),
                struct(name = "RNLU", src = triangular_level3.right_src, defines = ["UNIT"]),
                struct(name = "RNLN", src = triangular_level3.right_src, defines = []),
                struct(name = "RTUU", src = triangular_level3.right_src, defines = ["TRANSA", "UPPER", "UNIT"]),
                struct(name = "RTUN", src = triangular_level3.right_src, defines = ["TRANSA", "UPPER"]),
                struct(name = "RTLU", src = triangular_level3.right_src, defines = ["TRANSA", "UNIT"]),
                struct(name = "RTLN", src = triangular_level3.right_src, defines = ["TRANSA"]),
                struct(name = "RRUU", src = triangular_level3.right_src, defines = ["CONJ", "UPPER", "UNIT"]),
                struct(name = "RRUN", src = triangular_level3.right_src, defines = ["CONJ", "UPPER"]),
                struct(name = "RRLU", src = triangular_level3.right_src, defines = ["CONJ", "UNIT"]),
                struct(name = "RRLN", src = triangular_level3.right_src, defines = ["CONJ"]),
                struct(name = "RCUU", src = triangular_level3.right_src, defines = ["TRANSA", "CONJ", "UPPER", "UNIT"]),
                struct(name = "RCUN", src = triangular_level3.right_src, defines = ["TRANSA", "CONJ", "UPPER"]),
                struct(name = "RCLU", src = triangular_level3.right_src, defines = ["TRANSA", "CONJ", "UNIT"]),
                struct(name = "RCLN", src = triangular_level3.right_src, defines = ["TRANSA", "CONJ"]),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_%s" % (precision.prefix, triangular_level3.name, tri_variant.name.lower()),
                    src = tri_variant.src,
                    defines = precision.kernel_defines + tri_variant.defines,
                    symbol = "%s%s_%s" % (precision.prefix, triangular_level3.name, tri_variant.name),
                )
            for copy_variant in [
                struct(name = "iunucopy", src = "%s_uncopy_2.c" % triangular_level3.copy_src_prefix, defines = ["UNIT"]),
                struct(name = "iunncopy", src = "%s_uncopy_2.c" % triangular_level3.copy_src_prefix, defines = []),
                struct(name = "ilnucopy", src = "%s_lncopy_2.c" % triangular_level3.copy_src_prefix, defines = ["UNIT"]),
                struct(name = "ilnncopy", src = "%s_lncopy_2.c" % triangular_level3.copy_src_prefix, defines = []),
                struct(name = "iutucopy", src = "%s_utcopy_2.c" % triangular_level3.copy_src_prefix, defines = ["UNIT"]),
                struct(name = "iutncopy", src = "%s_utcopy_2.c" % triangular_level3.copy_src_prefix, defines = []),
                struct(name = "iltucopy", src = "%s_ltcopy_2.c" % triangular_level3.copy_src_prefix, defines = ["UNIT"]),
                struct(name = "iltncopy", src = "%s_ltcopy_2.c" % triangular_level3.copy_src_prefix, defines = []),
                struct(name = "ounucopy", src = "%s_uncopy_2.c" % triangular_level3.copy_src_prefix, defines = ["UNIT"]),
                struct(name = "ounncopy", src = "%s_uncopy_2.c" % triangular_level3.copy_src_prefix, defines = []),
                struct(name = "olnucopy", src = "%s_lncopy_2.c" % triangular_level3.copy_src_prefix, defines = ["UNIT"]),
                struct(name = "olnncopy", src = "%s_lncopy_2.c" % triangular_level3.copy_src_prefix, defines = []),
                struct(name = "outucopy", src = "%s_utcopy_2.c" % triangular_level3.copy_src_prefix, defines = ["UNIT"]),
                struct(name = "outncopy", src = "%s_utcopy_2.c" % triangular_level3.copy_src_prefix, defines = []),
                struct(name = "oltucopy", src = "%s_ltcopy_2.c" % triangular_level3.copy_src_prefix, defines = ["UNIT"]),
                struct(name = "oltncopy", src = "%s_ltcopy_2.c" % triangular_level3.copy_src_prefix, defines = []),
            ]:
                _openblas_object(
                    targets = targets,
                    name = "%s%s_%s" % (precision.prefix, triangular_level3.copy_prefix, copy_variant.name),
                    src = "kernel/generic/%s" % copy_variant.src,
                    defines = precision.kernel_defines + copy_variant.defines,
                    symbol = "%s%s_%s" % (precision.prefix, triangular_level3.copy_prefix, copy_variant.name),
                )
        for trmm_kernel in [
            struct(name = "LN", defines = ["TRMMKERNEL", "LEFT", "NN"]),
            struct(name = "LT", defines = ["TRMMKERNEL", "LEFT", "TRANSA", "NN"]),
            struct(name = "LR", defines = ["TRMMKERNEL", "LEFT", "CONJ", "CN"]),
            struct(name = "LC", defines = ["TRMMKERNEL", "LEFT", "TRANSA", "CONJ", "CN"]),
            struct(name = "RN", defines = ["TRMMKERNEL", "NN"]),
            struct(name = "RT", defines = ["TRMMKERNEL", "TRANSA", "NN"]),
            struct(name = "RR", defines = ["TRMMKERNEL", "CONJ", "NC"]),
            struct(name = "RC", defines = ["TRMMKERNEL", "TRANSA", "CONJ", "NC"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%strmm_kernel_%s" % (precision.prefix, trmm_kernel.name.lower()),
                src = "kernel/generic/ztrmmkernel_2x2.c",
                defines = precision.kernel_defines + trmm_kernel.defines,
                symbol = "%strmm_kernel_%s" % (precision.prefix, trmm_kernel.name),
            )
        for trsm_kernel in [
            struct(name = "LN", src = "kernel/generic/trsm_kernel_LN.c", defines = ["TRSMKERNEL", "UPPER", "LN"]),
            struct(name = "LT", src = "kernel/generic/trsm_kernel_LT.c", defines = ["TRSMKERNEL", "LT"]),
            struct(name = "LR", src = "kernel/generic/trsm_kernel_LN.c", defines = ["TRSMKERNEL", "UPPER", "LN", "CONJ"]),
            struct(name = "LC", src = "kernel/generic/trsm_kernel_LT.c", defines = ["TRSMKERNEL", "LT", "CONJ"]),
            struct(name = "RN", src = "kernel/generic/trsm_kernel_RN.c", defines = ["TRSMKERNEL", "UPPER", "RN"]),
            struct(name = "RT", src = "kernel/generic/trsm_kernel_RT.c", defines = ["TRSMKERNEL", "RT"]),
            struct(name = "RR", src = "kernel/generic/trsm_kernel_RN.c", defines = ["TRSMKERNEL", "UPPER", "RN", "CONJ"]),
            struct(name = "RC", src = "kernel/generic/trsm_kernel_RT.c", defines = ["TRSMKERNEL", "RT", "CONJ"]),
        ]:
            _openblas_object(
                targets = targets,
                name = "%strsm_kernel_%s" % (precision.prefix, trsm_kernel.name.lower()),
                src = trsm_kernel.src,
                defines = precision.kernel_defines + trsm_kernel.defines,
                symbol = "%strsm_kernel_%s" % (precision.prefix, trsm_kernel.name),
            )

    return targets

def openblas_level1_real_targets():
    return openblas_real_targets()
