alias(
    name = "csv_fast",
    actual = "//apps/csv_fast:csv_fast",
    visibility = ["//visibility:public"],
)

alias(
    name = "csv_fast_headers",
    actual = "//apps/csv_fast:csv_fast_headers",
    visibility = ["//visibility:public"],
)
